version: '3'

services:
  gobarber_base:
    build: .

  go-barber-api:
    container_name: gobarber-api
    extends: gobarber_base
    command: yarn dev:server
    volumes:
      - .:/usr/app/
    depends_on:
      - postgres-db
    ports:
      - "3333:3333"

  postgres-db:
    container_name: gobarber-postgres
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  migration:
    extends: gobarber_base
    command: yarn typeorm migration:run
    depends_on:
      - postgres-db
